#pragma once
constexpr char kGeniusPortalPage[] =
    R"HTML(<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Genius Generic 2.5.0</title>
<style>body{font:16px system-ui;background:#f3f5f8;color:#172336;margin:0}main{max-width:780px;margin:30px auto;padding:0 20px}section{background:white;padding:22px;border-radius:16px;margin:20px 0}h1{font-size:30px}h2{font-size:21px}input,button{box-sizing:border-box;width:100%;font:inherit;padding:11px;border:1px solid #cad2de;border-radius:8px;margin:8px 0}button{background:#245ce4;color:white;border:0;cursor:pointer}.row{display:flex;gap:10px}.row button{width:auto;flex:1}.secondary{background:#e9eef8;color:#18345d}p,small{color:#58677a;line-height:1.5}#message{white-space:pre-wrap;background:#e9f0ff;padding:16px;border-radius:10px}li{margin:10px 0}</style>
<main><p>GENIUS DEVICE</p><h1>Genius Generic 2.5.0</h1><p id="status">Memuat perangkat…</p><div id="message" role="status">Media · Alarm · EWS</div>
<section><h2>Radio & musik</h2><p>Putar URL langsung MP3, AAC/ADTS, WAV/PCM atau Ogg/Opus mono.</p><label>Judul<input id="title" maxlength="128" value="Radio"></label><label>URL audio<input id="url" maxlength="2048" type="url" placeholder="https://…"></label><div class="row"><button id="play">Putar</button><button class="secondary" id="stop">STOP</button></div><small>Alarm/EWS mengambil alih audio. Setelah selesai, radio dimulai kembali dari URL. STOP dan BOOT membatalkan pemutaran serta resume.</small></section>
<section><h2>Alarm native</h2><p>Jadwal disimpan di perangkat. Alarm lokal memakai bunyi embedded dan tetap dapat berjalan tanpa internet setelah jam tersinkron.</p><label>ID alarm<input id="alarmId" maxlength="48" value="alarm-1"></label><label>Label<input id="label" maxlength="96" value="Alarm"></label><label>Waktu alarm<input id="due" type="datetime-local"></label><label>Ulang setiap (detik;0 = sekali)<input id="repeat" type="number" min="0" max="604800" value="0"></label><div class="row"><button id="set">Simpan</button><button class="secondary" id="cancel">Hapus</button><button class="secondary" id="ring">Uji bunyi</button></div><ul id="alarms"></ul></section>
<section><h2>EWS · BMKG</h2><p>Peringatan memakai data gempa resmi BMKG, bunyi peringatan lokal, lalu pembacaan info BMKG ketika audio ucapan tersedia.</p><p id="bmkg">Menunggu data BMKG…</p><div class="row"><button id="check">Periksa BMKG</button><button class="secondary" id="ewsTest">Uji chime BMKG</button></div><label><input id="enabled" type="checkbox" style="width:auto">Aktifkan pemeriksaan EWS</label><p>Uji info terakhir adalah tes perangkat, bukan peringatan gempa baru. Pembacaan suara menunggu integrasi Genius; bunyi peringatan lokal sudah tersedia.</p></section>
<section><h2>Wi-Fi</h2><p>Tahan BOOT2 detik, sambungkan ke hotspot perangkat, lalu buka http://192.168.4.1/. Pengaturan GPIO, battery, dan wajah kawaii akan ditambahkan pada tahap berikutnya.</p></section></main>
<script>let token='';const el=id=>document.getElementById(id);function msg(text){el('message').textContent=text}async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Genius-Token':token}:{},body:body?JSON.stringify(body):undefined});const value=await r.json();if(!r.ok)throw Error(value.error||'Permintaan gagal');return value}async function run(fn){try{await fn()}catch(e){msg(e.message)}}
el('play').onclick=()=>run(async()=>{await api('/api/media',{action:'play',url:el('url').value,title:el('title').value});msg('Media diterima.')});el('stop').onclick=()=>run(async()=>{await api('/api/media',{action:'stop'});msg('Pemutaran dihentikan.')});el('set').onclick=()=>run(async()=>{const epoch=new Date(el('due').value).getTime()/1000;if(!Number.isFinite(epoch))throw Error('Pilih waktu alarm.');await api('/api/alarm',{action:'set',alarm_id:el('alarmId').value,label:el('label').value,due_epoch:epoch,repeat_seconds:Number(el('repeat').value)});msg('Alarm tersimpan.');await refresh()});el('cancel').onclick=()=>run(async()=>{await api('/api/alarm',{action:'cancel',alarm_id:el('alarmId').value});msg('Alarm dihapus.');await refresh()});el('ring').onclick=()=>run(async()=>{await api('/api/alarm',{action:'ring',label:el('label').value});msg('Alarm uji berbunyi; STOP untuk menghentikan.')});el('check').onclick=()=>run(async()=>{await api('/api/ews',{action:'check'});msg('Pemeriksaan BMKG diminta.')});el('ewsTest').onclick=()=>run(async()=>{await api('/api/ews',{action:'test'});msg('Chime info BMKG terakhir diminta; pembacaan suara menunggu audio dari Genius.')});el('enabled').onchange=()=>run(async()=>{await api('/api/ews',{action:'configure',enabled:el('enabled').checked});msg('Pengaturan EWS tersimpan.')});async function refresh(){const data=await api('/api/config');token=data.token;el('status').textContent=data.state+' · '+(data.playback.state||'idle')+' · media='+data.capabilities.media+' alarm='+data.capabilities.alarm+' ews='+data.capabilities.ews;el('enabled').checked=data.native.ews_enabled;el('bmkg').textContent=data.native.bmkg_text||data.native.ews_error||'Menunggu data BMKG…';el('alarms').replaceChildren();for(const alarm of data.native.alarms){const li=document.createElement('li');li.textContent=alarm.label+' · '+new Date(alarm.due_epoch*1000).toLocaleString();el('alarms').append(li)}}run(refresh);setInterval(()=>run(refresh),3000);</script></html>)HTML";
